print("How old are you?", end=' ')
age = input()
print("How tall are you?", end=' ')
height = input()
print("How much do you weigh?", end=' ')
weight = input()
print("What's your hobby?", end=' ')
hobby = input()
print(f"So, you're {age} old, {height} tall and {weight} heavy. And you like {hobby}")

